language: node_js
node_js:
  - "stable"
services:
  - docker
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

