language: node_js
node_js:
  - "stable"
services:
  - docker
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - npm run build
after_script: # Upload coverage reports
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
before_deploy:
  # Set up git user name and tag this commits
  - git config --local user.name "bonkzero404"
  - git config --local user.email "bonkzero404@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist/web
